# Generated by Django 4.0.4 on 2022-04-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='senderwallet',
            old_name='last_updated',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='publicwallet',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='senderwallet',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='senderwallet',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
