# Generated by Django 4.0.4 on 2022-04-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_last_updated_senderwallet_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicwallet',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publicwallet',
            name='total_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publicwallet',
            name='total_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publicwallet',
            name='unconfirmed_balance',
            field=models.IntegerField(default=0),
        ),
    ]
