# Generated by Django 4.0.4 on 2022-04-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_publicwallet_balance_publicwallet_total_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='senderwallet',
            name='total_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='senderwallet',
            name='total_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='senderwallet',
            name='unconfirmed_balance',
            field=models.IntegerField(default=0),
        ),
    ]
