# Generated by Django 4.0.4 on 2022-04-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_senderwallet_private_senderwallet_public_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSenderWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('public', models.CharField(default='', max_length=150)),
                ('private', models.CharField(default='', max_length=150)),
                ('address', models.CharField(default='', max_length=150)),
                ('balance', models.IntegerField(default=0)),
                ('unconfirmed_balance', models.IntegerField(default=0)),
                ('total_received', models.IntegerField(default=0)),
                ('total_sent', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
