# Generated by Django 4.0.4 on 2022-05-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_activesenderwallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesenderwallet',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='senderwallet',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
    ]
