# Generated by Django 4.0.4 on 2022-05-04 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_activesenderwallet_activesenderwallet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveSenderWallet',
        ),
        migrations.CreateModel(
            name='ActiveSenderWallet',
            fields=[
                ('senderwallet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.senderwallet')),
            ],
            options={
                'abstract': False,
            },
            bases=('api.senderwallet',),
        ),
    ]
