# Generated by Django 4.0.4 on 2022-05-04 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_activesenderwallet_activesenderwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='activesenderwallet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
