# Generated by Django 4.0.4 on 2022-05-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_activesenderwallet_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activesenderwallet',
            name='is_active',
        ),
        migrations.AddField(
            model_name='senderwallet',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
