# Generated by Django 4.0.4 on 2022-05-04 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_activesenderwallet_is_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveSenderWallet',
        ),
    ]
